# databases:
#   - name: shopify
#     databaseName: shopify
#     user: shopify



services:
  - type: web
    name: shopify
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn shopify.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shopify
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
